# Generated by Django 3.1.5 on 2021-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210110_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
